// src/sanitizer/defaultSanitizerConfig.ts
import { Config } from "dompurify";

/**
 * Default DOMPurify sanitization configuration that matches Parcel Editor capabilities.
 * This configuration allows HTML elements and attributes that can be generated by the
 * Parcel Editor with standard formatting extensions.
 */
export const defaultSanitizerConfig: Config = {
  // Allow elements from Parcel Editor
  ALLOWED_TAGS: [
    // Block elements
    "p",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "blockquote",
    "pre",
    "code",

    // List elements
    "ul",
    "ol",
    "li",

    // Inline formatting
    "strong",
    "em",
    "del",
    "s",
    "u",
    "a",
    "code",

    // Special elements
    "br",
    "hr",

    // Table elements (optional, not in your current config)
    // 'table', 'tbody', 'thead', 'tr', 'td', 'th',

    // Containers that might be used
    "div",
    "span",
  ],

  // Allow attributes commonly used by Parcel Editor
  ALLOWED_ATTR: [
    // Links
    "href",
    "rel",

    // Text alignment
    "style",
    "align",
    "class",

    // General attributes
    "id",
    "data-type",
    "data-align",
  ],

  // Preserve as much as possible while removing dangerous content
  KEEP_CONTENT: true,

  // Don't allow potentially dangerous URLs
  FORBID_TAGS: [
    "script",
    "style",
    "iframe",
    "frame",
    "object",
    "embed",
    "form",
    "input",
    "button",
  ],
  FORBID_ATTR: [
    "onerror",
    "onload",
    "onclick",
    "onmouseover",
    "onmouseout",
    "formaction",
    "target",
  ],
};
